[package]
name = "rust_native"
version = "0.1.0"
authors = ["jhodgson91 <jhodgson71@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "__rust_native"
crate-type = ["dylib"]

[dependencies]